### ISSUE TITLE
How to hide item in menu left

### ISSUE THREAD

**Issue by nhoctanker** [mledour/angular-admin-lte#35]
How to hide and show menu item with role user ? please help me .

**Comment by giquieu** [comment]
Hello, since the Menu Items are configured by an Object (LayoutModule.forRoot), you could create a Service, where for example when entering the system this service would fetch the menus released from the respective user that logged in.

**Comment by nhoctanker** [comment]
@giquieu  Please give me exmple . im new in angular 2+

**Comment by Mihai-B** [comment]
If you want to hide items in the left menu, just use the layout service to add items based on roles or what other criteria you chose like so:

`import { LayoutStore } from 'angular-admin-lte';`

```
const routeChildren = [];

 const menuItems = [];

routeChildren.push({ label: 'Persons', route: 'cpanel/person', iconClasses: 'fa  fa-group' });
menuItems.push({
      label: 'Control Panel', iconClasses: 'fa  fa-gears', children: routeChildren
    });
 this.layoutStore.setSidebarLeftMenu(menuItems);
```

Hope this helps

**Comment by piecho1991** [comment]
@Mihai-B This is works but after change component... 

Items in Layout was updated but not component after `this.layoutStore.setSidebarLeftMenu(menuItems);`

Could you write any exacple how to use it ?

**Comment by nhoctanker** [comment]
Yes i need Any exacple how to use it . and where to put this code ?

**Comment by iyilm4z** [comment]
@nhoctanker my friend, usually a role is assigned to a user and the role has permissions. In order to detect current user's roles he/she should be logged-in right? The answer is yes. 

Okay we know current user and roles assigned to him/her and we want dynamically render the menu for him/her. In this process you should hook into app init process of angular. Angular already has this feature. [Here ](https://www.intertech.com/Blog/angular-4-tutorial-run-code-during-app-initialization/)is a nice article about it which can give you an idea.

If i were you i would write an APP_INITIALIZER factory method and get roles of current user and detect granted menu items for him/here and set it to a variable in an service. By the way services in angular has singleton lifecycle. It means you can get granted menu items for the current user from everywhere by using that service. 

I hope this helps you.
